POST http://localhost:8080/checkAuth


{
    "permission": {
        "user_name":"Thomas",
        "password":"password",
        "app_id":2,
        "grants":"user"
        },
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6NCwiYXV0aG9yaXplZCI6dHJ1ZSwiZXhwIjoxNzM2OTc2MTg1LCJncmFudHMiOiIiLCJ1c2VyIjoibWlsZXMifQ.5KLhZXA806wFzTYljr8uLGjKxbE_eYA1c7DiBjbDHic"
}